server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend_service_logs
    static_configs:
      - targets:
          - localhost
        labels:
          service_name: backend-service-development-harsh
          __path__: /var/log/server.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            timestamp: time
      - labels:
          service_name: backend-service-development-harsh
          stream: server
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: output

  - job_name: processor_service_logs
    static_configs:
      - targets:
          - localhost
        labels:
          service_name: processor-service-development-harsh
          __path__: /var/log/processor-service.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            timestamp: time
      - labels:
          service_name: processor-service-development-harsh
          stream: processor
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: output

  - job_name: cron_job_logs
    static_configs:
      - targets:
          - localhost
        labels:
          service_name: cron-jobs-development-harsh
          __path__: /var/log/cron-jobs.log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            timestamp: time
      - labels:
          service_name: cron-jobs-development-harsh
          stream: cron
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: output
